#!/usr/bin/env php
<?php

require dirname(__DIR__, 3) . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__ . '/.env');
$dotenv->load();

$application = new Application();
$application->add(new RzCommon\graphql\Command\CreateTypeCommand);
$application->run();